### ISSUE TITLE
Cannot deploy conformant bundles with storage constraints 

### ISSUE THREAD

**Issue by addyess** [juju/python-libjuju#1060]
### Description

I've added a new test where a bundle is deployed with storage constraints

Within that bundle we're deploying an applications which lists storage constraints

```yaml
  ceph-osd:
    charm: ceph-osd
    channel: quincy/stable
    constraints: cores=2 mem=4G root-disk=16G
    num_units: 1
    storage:
      osd-devices: 1G,2
      osd-journals: 1G,1
```

when using `model.deploy(...)` against this bundle, pylib juju tries to parse the values of `osd-devices` and `osd-journals` as if they are json.  

If i change them to json, 

```yaml
  ceph-osd:
    charm: ceph-osd
    channel: quincy/stable
    constraints: cores=2 mem=4G root-disk=16G
    num_units: 1
    storage:
      osd-devices: '{"size": "1G", "count": 2}'
      osd-journals: '{"size": "1G", "count": 1}'
```

then the library fails to fetch the plan.  

There doesn't seem much to be done about getting these constraints working.

what's odd is that `test_deploy_bundle_with_storage_constraint` in `test_model.py` looks to me like it should actually test this exact issue.  So i'm not sure what's different about my case vs the one already tested. 

### Urgency

Casually reporting

### Python-libjuju version

3.5.0.0

### Juju version

3.3.5

### Reproduce / Test

```python
@base.bootstrapped
@pytest.mark.bundle
async def test_deploy_bundle_with_storage_constraint():
    bundle_path = INTEGRATION_TEST_DIR / 'bundle' / 'bundle-with-storage-constraint.yaml'

    async with base.CleanModel() as model:
        await model.deploy(bundle_path)
        await wait_for_bundle(model, bundle_path)
        storage = await model.list_storage()
        assert len(storage) == 1
```
