### ISSUE TITLE
when deploying a bundle, resource revisions are ignored

### ISSUE THREAD

**Issue by Cynerva** [juju/python-libjuju#273]
Deploy a bundle that includes something like this:

```
services:
  flannel:
    charm: cs:~containers/flannel-339
    resources:
      flannel-amd64: 3
      flannel-arm64: 1
      flannel-s390x: 3
```

Instead of getting the specified bundle revisions, you'll get whichever revisions the charm store gives you (in this case, the latest resources from the edge channel). In contrast, if you deploy via Juju CLI, you will get the specified revisions.

The issue occurs [here](https://github.com/juju/python-libjuju/blob/87d9388191edfcfea804a563125e5634bba53db9/juju/model.py#L2053), where the `resources` that are passed in _do_ include the revision numbers, but that parameter is ignored.
