### ISSUE TITLE
No way to retrieve complete action output

### ISSUE THREAD

**Issue by AdamIsrael** [juju/python-libjuju#325]
In `juju/model.py`, the `get_action_output` method only returns the output from the action, but there is more information available that doesn't have a path for exposure.

Here is the return from `juju show-action-status $uuid`:
```
message: This action has failed.
results:
  success: "False"
status: failed
timing:
  completed: 2019-07-24 16:16:34 +0000 UTC
  enqueued: 2019-07-24 16:16:29 +0000 UTC
  started: 2019-07-24 16:16:33 +0000 UTC
```
The `get_action_output` method only returns:
```
{'success': 'False'}
```
Of specific interest is getting the message returned by the output. This is important when an action has failed; there's no way to get that message from either `get_action_output` or `get_action_status`.

I'm not sure the best place to implement this; doing it in `get_action_output` feels like the right place, but it would break compatibility, because we'd need to return something like:
```
{
'message': 'This action has failed.',
'results': {
    'success': 'False',
},
'status': 'failed,
[...]
}
```

Or add new methods, ie., `get_action_message` to retrieve that particular field.
