### ISSUE TITLE
Local resources not implemented in local bundles

### ISSUE THREAD

**Issue by davigar15** [juju/python-libjuju#522]
Local resources for oci-images were added for charm deployments, not for bundles.

Example of a bundle that doesn't work:

```yaml
bundle: kubernetes
applications:
  onos2:
    charm: "../charms/onos.charm"
    scale: 1
    options:
      admin-password: admin
    resources:
      onos-image: onosproject/onos:2.6.0
```
