### ISSUE TITLE
Image pull errors when trying to deploy bundles with sidecar charms with libjuju

### ISSUE THREAD

**Issue by gcalvinos** [juju/python-libjuju#677]
When trying to deploy a bundle with **sidecar** charms with libjuju, I got an ImagePullBackOff error.

I use python libjuju 2.9.9, juju 2.9.29 and microk8s 1.23

This is the bundle I deploy:

```
bundle: kubernetes
name: magma-orc8r
description: |
  Orchestrator is a Magma service that provides a simple and consistent way to 
  configure and monitor the wireless network securely. The metrics acquired through the platform 
  allows you to see the analytics and traffic flows of the wireless users through the Magma web UI.
applications:
  nms-magmalte:
    charm: magma-nms-magmalte
    channel: edge
    scale: 1
    trust: true
  nms-nginx-proxy:
    charm: magma-nms-nginx-proxy
    channel: edge
    scale: 1
    trust: true
  orc8r-accessd:
    charm: magma-orc8r-accessd
    channel: edge
    scale: 1
    trust: true
  orc8r-alertmanager:
    charm: alertmanager-k8s
    channel: edge
    scale: 1
    trust: true
  orc8r-analytics:
    charm: magma-orc8r-analytics
    channel: edge
    scale: 1
    trust: true
  orc8r-bootstrapper:
    charm: magma-orc8r-bootstrapper
    channel: edge
    scale: 1
    trust: true
  orc8r-certifier:
    charm: magma-orc8r-certifier
    channel: edge
    scale: 1
    trust: true
    options:
      domain: magma-orc.com
  orc8r-configurator:
    charm: magma-orc8r-configurator
    channel: edge
    scale: 1
    trust: true
  orc8r-ctraced:
    charm: magma-orc8r-ctraced
    channel: edge
    scale: 1
    trust: true
  orc8r-device:
    charm: magma-orc8r-device
    channel: edge
    scale: 1
    trust: true
  orc8r-directoryd:
    charm: magma-orc8r-directoryd
    channel: edge
    scale: 1
    trust: true
  orc8r-dispatcher:
    charm: magma-orc8r-dispatcher
    channel: edge
    scale: 1
    trust: true
  orc8r-eventd:
    charm: magma-orc8r-eventd
    channel: edge
    scale: 1
    trust: true
    options:
      elasticsearch-url: "orc8r-elasticsearch:1234"
  orc8r-ha:
    charm: magma-orc8r-ha
    channel: edge
    scale: 1
    trust: true
  orc8r-lte:
    charm: magma-orc8r-lte
    channel: edge
    scale: 1
    trust: true
  orc8r-metricsd:
    charm: magma-orc8r-metricsd
    channel: edge
    scale: 1
    trust: true
  orc8r-nginx:
    charm: magma-orc8r-nginx
    channel: edge
    scale: 1
    trust: true
  orc8r-obsidian:
    charm: magma-orc8r-obsidian
    channel: edge
    scale: 1
    trust: true
  orc8r-orchestrator:
    charm: magma-orc8r-orchestrator
    channel: edge
    scale: 1
    trust: true
    options:
      elasticsearch-url: "orc8r-elasticsearch:1234"
  orc8r-policydb:
    charm: magma-orc8r-policydb
    channel: edge
    scale: 1
    trust: true
  orc8r-prometheus:
    charm: prometheus-k8s
    channel: edge
    scale: 1
    trust: true
  orc8r-prometheus-cache:
    charm: prometheus-edge-hub
    channel: edge
    scale: 1
    trust: true
    options:
      metrics_count_limit: 500000
  orc8r-service-registry:
    charm: magma-orc8r-service-registry
    channel: edge
    scale: 1
    trust: true
  orc8r-smsd:
    charm: magma-orc8r-smsd
    channel: edge
    scale: 1
    trust: true
  orc8r-state:
    charm: magma-orc8r-state
    channel: edge
    scale: 1
    trust: true
  orc8r-streamer:
    charm: magma-orc8r-streamer
    channel: edge
    scale: 1
    trust: true
  orc8r-subscriberdb:
    charm: magma-orc8r-subscriberdb
    channel: edge
    scale: 1
    trust: true
  orc8r-subscriberdb-cache:
    charm: magma-orc8r-subscriberdb-cache
    channel: edge
    scale: 1
    trust: true
  orc8r-tenants:
    charm: magma-orc8r-tenants
    channel: edge
    scale: 1
    trust: true
  orc8r-user-grafana:
    charm: grafana-k8s
    channel: edge
    options:
      web_external_url: "/grafana"
    scale: 1
    trust: true
  postgresql-k8s:
    charm: postgresql-k8s
    series: kubernetes
    channel: stable
    scale: 1
    trust: true
relations:
- - nms-magmalte:certifier
  - orc8r-certifier:certifier
- - nms-magmalte:db
  - postgresql-k8s:db
- - nms-nginx-proxy:certifier
  - orc8r-certifier:certifier
- - nms-nginx-proxy:magmalte
  - nms-magmalte:magmalte
- - orc8r-accessd:db
  - postgresql-k8s:db
- - orc8r-bootstrapper:certifier
  - orc8r-certifier:certifier
- - orc8r-certifier:db
  - postgresql-k8s:db
- - orc8r-configurator:db
  - postgresql-k8s:db
- - orc8r-ctraced:db
  - postgresql-k8s:db
- - orc8r-device:db
  - postgresql-k8s:db
- - orc8r-directoryd:db
  - postgresql-k8s:db
- - orc8r-lte:db
  - postgresql-k8s:db
- - orc8r-nginx:bootstrapper
  - orc8r-bootstrapper:bootstrapper
- - orc8r-nginx:certifier
  - orc8r-certifier:certifier
- - orc8r-nginx:obsidian
  - orc8r-obsidian:obsidian
- - orc8r-orchestrator:certifier
  - orc8r-certifier:certifier
- - orc8r-policydb:db
  - postgresql-k8s:db
- - orc8r-prometheus:alertmanager
  - orc8r-alertmanager:alerting
- - orc8r-prometheus
  - orc8r-prometheus-cache
- - orc8r-prometheus
  - orc8r-user-grafana
- - orc8r-smsd:db
  - postgresql-k8s:db
- - orc8r-state:db
  - postgresql-k8s:db
- - orc8r-subscriberdb-cache:db
  - postgresql-k8s:db
- - orc8r-subscriberdb:db
  - postgresql-k8s:db
- - orc8r-tenants:db
  - postgresql-k8s:db
```

And this is the status of the deployment in the K8s cluster:

```
$ microk8s kubectl get pods -A
NAMESPACE                                            NAME                                       READY   STATUS             RESTARTS   AGE
kube-system                                          coredns-64c6478b6c-pr7ms                   1/1     Running            0          7d6h
kube-system                                          calico-kube-controllers-7ddfc9fc55-ttrw4   1/1     Running            0          7d6h
kube-system                                          calico-node-cfmpg                          1/1     Running            0          7d6h
kube-system                                          hostpath-provisioner-7764447d7c-hjxkm      1/1     Running            0          7d6h
ingress                                              nginx-ingress-microk8s-controller-bhn65    1/1     Running            0          7d6h
kube-system                                          tiller-deploy-57c7c4f55-29mzf              1/1     Running            0          7d5h
container-registry                                   registry-5f697bb7df-rv2g4                  1/1     Running            0          29h
metallb-system                                       speaker-lcx2q                              1/1     Running            0          174m
metallb-system                                       controller-558b7b958-b5xwf                 1/1     Running            0          174m
magma-orc-kdu-68e71735-18e6-464d-b9e7-e864e0af065d   modeloperator-758f6ff44c-8wfqx             1/1     Running            0          24m
magma-orc-kdu-68e71735-18e6-464d-b9e7-e864e0af065d   postgresql-k8s-operator-0                  1/1     Running            0          20m
magma-orc-kdu-68e71735-18e6-464d-b9e7-e864e0af065d   postgresql-k8s-0                           1/1     Running            0          17m
magma-orc-kdu-68e71735-18e6-464d-b9e7-e864e0af065d   orc8r-alertmanager-0                       1/2     ImagePullBackOff   0          21m
magma-orc-kdu-68e71735-18e6-464d-b9e7-e864e0af065d   orc8r-analytics-0                          1/2     ImagePullBackOff   0          21m
magma-orc-kdu-68e71735-18e6-464d-b9e7-e864e0af065d   orc8r-bootstrapper-0                       1/2     ImagePullBackOff   0          20m
magma-orc-kdu-68e71735-18e6-464d-b9e7-e864e0af065d   orc8r-certifier-0                          1/2     ImagePullBackOff   0          20m
magma-orc-kdu-68e71735-18e6-464d-b9e7-e864e0af065d   orc8r-configurator-0                       1/2     ImagePullBackOff   0          20m
magma-orc-kdu-68e71735-18e6-464d-b9e7-e864e0af065d   orc8r-device-0                             1/2     ImagePullBackOff   0          20m
magma-orc-kdu-68e71735-18e6-464d-b9e7-e864e0af065d   orc8r-dispatcher-0                         1/2     ImagePullBackOff   0          20m
magma-orc-kdu-68e71735-18e6-464d-b9e7-e864e0af065d   orc8r-ctraced-0                            1/2     ImagePullBackOff   0          20m
magma-orc-kdu-68e71735-18e6-464d-b9e7-e864e0af065d   orc8r-directoryd-0                         1/2     ImagePullBackOff   0          20m
magma-orc-kdu-68e71735-18e6-464d-b9e7-e864e0af065d   orc8r-eventd-0                             1/2     ImagePullBackOff   0          20m
magma-orc-kdu-68e71735-18e6-464d-b9e7-e864e0af065d   nms-nginx-proxy-0                          1/2     ImagePullBackOff   0          20m
magma-orc-kdu-68e71735-18e6-464d-b9e7-e864e0af065d   orc8r-ha-0                                 1/2     ImagePullBackOff   0          20m
magma-orc-kdu-68e71735-18e6-464d-b9e7-e864e0af065d   orc8r-nginx-0                              1/2     ImagePullBackOff   0          19m
magma-orc-kdu-68e71735-18e6-464d-b9e7-e864e0af065d   orc8r-lte-0                                1/2     ImagePullBackOff   0          20m
magma-orc-kdu-68e71735-18e6-464d-b9e7-e864e0af065d   orc8r-metricsd-0                           1/2     ImagePullBackOff   0          19m
magma-orc-kdu-68e71735-18e6-464d-b9e7-e864e0af065d   orc8r-accessd-0                            1/2     ImagePullBackOff   0          19m
magma-orc-kdu-68e71735-18e6-464d-b9e7-e864e0af065d   orc8r-orchestrator-0                       1/2     ImagePullBackOff   0          19m
magma-orc-kdu-68e71735-18e6-464d-b9e7-e864e0af065d   orc8r-obsidian-0                           1/2     ImagePullBackOff   0          19m
magma-orc-kdu-68e71735-18e6-464d-b9e7-e864e0af065d   orc8r-prometheus-cache-0                   1/2     ImagePullBackOff   0          19m
magma-orc-kdu-68e71735-18e6-464d-b9e7-e864e0af065d   orc8r-service-registry-0                   1/2     ImagePullBackOff   0          19m
magma-orc-kdu-68e71735-18e6-464d-b9e7-e864e0af065d   orc8r-policydb-0                           1/2     ImagePullBackOff   0          19m
magma-orc-kdu-68e71735-18e6-464d-b9e7-e864e0af065d   orc8r-subscriberdb-cache-0                 1/2     ImagePullBackOff   0          19m
magma-orc-kdu-68e71735-18e6-464d-b9e7-e864e0af065d   orc8r-prometheus-0                         1/2     ImagePullBackOff   0          19m
magma-orc-kdu-68e71735-18e6-464d-b9e7-e864e0af065d   orc8r-smsd-0                               1/2     ImagePullBackOff   0          19m
magma-orc-kdu-68e71735-18e6-464d-b9e7-e864e0af065d   orc8r-state-0                              1/2     ImagePullBackOff   0          19m
magma-orc-kdu-68e71735-18e6-464d-b9e7-e864e0af065d   orc8r-subscriberdb-0                       1/2     ImagePullBackOff   0          19m
magma-orc-kdu-68e71735-18e6-464d-b9e7-e864e0af065d   orc8r-streamer-0                           1/2     ImagePullBackOff   0          19m
magma-orc-kdu-68e71735-18e6-464d-b9e7-e864e0af065d   orc8r-user-grafana-0                       1/2     ImagePullBackOff   0          19m
magma-orc-kdu-68e71735-18e6-464d-b9e7-e864e0af065d   orc8r-tenants-0                            1/2     ImagePullBackOff   0          19m
magma-orc-kdu-68e71735-18e6-464d-b9e7-e864e0af065d   nms-magmalte-0                             1/2     ImagePullBackOff   0          22m
```

I think this is related to this bug in Juju (the behaviour is exactly the same), but we don't include "series:kubernetes" in each application.
